### ISSUE TITLE
I can't get this to run

### ISSUE THREAD

**Issue by rmchale** [jamieconnolly/puppet-dotfiles#2]
When add include dotfiles nothing happens

**Comment by jamieconnolly** [comment]
Hi @rmchale, this module relies upon configuration to know what files to symlink, and from which repository. You can see some documentation around the Hiera configuration needed [here](https://github.com/jamieconnolly/puppet-dotfiles#hiera-configuration). I hope that helps.

**Comment by rmchale** [comment]
I put a file in `/opt/boxen/repo/hiera/users/rmchale.yaml` with similar configuration as above.  But I don't see it downloading my "dotfiles"  Is there some logging or a way to debug this?

**Comment by jamieconnolly** [comment]
You can run `boxen --debug`. That will give a lot more information about what is being processed. In that output you should be able to see if Hiera is loading in `users/rmchale.yaml`, and then subsequently what parts of the dotfiles module are getting called.

**Comment by rmchale** [comment]
Nothing about my rmchale.yaml in there.  Seems like my hiera is not
working.  I can start with that I suppose.  Does the plugin output anything
specific?

Ryan

---

http://blog.mchaler.org  http://twitter.com/rmchale
http://www.facebook.com/ryan.mchale

**Comment by jamieconnolly** [comment]
Here's some of the output I get when I run `boxen --debug`. I only configure `dotfiles::symlinks:` inside my personal hiera configuration, as I've tailored my dotfiles to the defaults of this module.

```
Debug: Automatically imported dotfiles::config from dotfiles/config into production
Debug: hiera(): Looking up dotfiles::dir in YAML backend
Debug: hiera(): Looking for data source users/jamieconnolly
Debug: hiera(): Looking for data source common
Debug: hiera(): Looking up dotfiles::dir in Module Data backend
Debug: hiera(): Looking for data in source /opt/boxen/repo/shared/dotfiles/data/common.yaml
Debug: hiera(): Looking up dotfiles::source in YAML backend
Debug: hiera(): Looking for data source users/jamieconnolly
Debug: hiera(): Looking for data source common
Debug: hiera(): Looking up dotfiles::source in Module Data backend
Debug: hiera(): Looking for data in source /opt/boxen/repo/shared/dotfiles/data/common.yaml
Debug: hiera(): Looking up dotfiles::prefix in YAML backend
Debug: hiera(): Looking for data source users/jamieconnolly
Debug: hiera(): Looking for data source common
Debug: hiera(): Looking up dotfiles::prefix in Module Data backend
Debug: hiera(): Looking for data in source /opt/boxen/repo/shared/dotfiles/data/common.yaml
Debug: hiera(): Looking up dotfiles::suffix in YAML backend
Debug: hiera(): Looking for data source users/jamieconnolly
Debug: hiera(): Looking for data source common
Debug: hiera(): Looking up dotfiles::suffix in Module Data backend
Debug: hiera(): Looking for data in source /opt/boxen/repo/shared/dotfiles/data/common.yaml
Debug: hiera(): Looking up dotfiles::symlinks in YAML backend
Debug: hiera(): Looking for data source users/jamieconnolly
Debug: hiera(): Found dotfiles::symlinks in users/jamieconnolly

Debug: Create new resource dotfiles::symlink[atom] with params { ... }

Debug: Repository[/Users/jamieconnolly/Code/dotfiles]: Adding default for provider
Debug: Repository[/Users/jamieconnolly/Code/dotfiles]: Adding default for extra
Debug: Repository[/Users/jamieconnolly/Code/dotfiles]: Adding default for require
Debug: Repository[/Users/jamieconnolly/Code/dotfiles]: Adding default for config

Debug: /Stage[main]/Dotfiles/Repository[/Users/jamieconnolly/Code/dotfiles]/require: requires File[/opt/boxen/bin/boxen-git-credential]
Debug: /Stage[main]/Dotfiles/Dotfiles::Symlink[atom]/require: requires Repository[/Users/jamieconnolly/Code/dotfiles]
```

Hope this helps when looking over the log.

**Comment by rmchale** [comment]
Thanks this was helpful.  I got it working.  I had to put the "include dotfiles" in my manifests/site.pp.   Is there anyway to have dotfiles in say bitbucket instead of github?

**Comment by jamieconnolly** [comment]
This module uses the [boxen/puppet-repository](https://github.com/boxen/puppet-repository) module to handle the repository location. I'm not sure on the whether BitBucket is supported through that. A quick search suggests that public git repositories might be possible, but I'm unsure on private repositories. Sorry I couldn't be more help.
